/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorBodega;
import controlador.ControladorCategoria;
import controlador.ControladorEmpleado;
import controlador.ControladorProducto;
import controlador.ControladorReceta;
import controlador.ControladorRecetaDetalle;
import controlador.ControladorSucursal;
import controlador.ControladorTipoMedida;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Administrador;


/**
 *
 * @author Isaac Chavez ECh
 */
public class AdministradorFrame extends javax.swing.JFrame {
    ControladorEmpleado ce;
    ControladorCategoria cc;
    ControladorTipoMedida ctm;
    ControladorProducto cp;
    ControladorReceta cr;
    ControladorRecetaDetalle crd;
    ControladorBodega cb;
    ControladorSucursal cs;
    Administrador adm;
    

    /**
     * Creates new form AdministradorFrame
     * @param cee
     * @param ccc
     * @param ctmm
     * @param cpp
     * @param cr
     * @param crd
     * @param cb
     * @param cs
     * @param adm
     */
    public AdministradorFrame(ControladorEmpleado cee, ControladorCategoria ccc,
                              ControladorTipoMedida ctmm, ControladorProducto cpp,
                              ControladorReceta cr, ControladorRecetaDetalle crd,
                              ControladorBodega cb, ControladorSucursal cs, Administrador adm) {
        initComponents();
        this.getContentPane().setBackground(new Color(125,125,125));
        this.ce = cee;
        this.cc = ccc;
        this.ctm = ctmm;
        this.cp = cpp;
        this.cr = cr;
        this.crd = crd;
        this.cb = cb;
        this.cs = cs;
        this.adm = adm;
        nombrel.setText(adm.getAdmUsername());
        apellidol.setText(adm.getPerCorreo());
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/user (3).png"));
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(imagenlb.getWidth(), imagenlb.getHeight(),Image.SCALE_DEFAULT));
        imagenlb.setIcon(fondo);
    }

    private AdministradorFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrel = new javax.swing.JLabel();
        apellidol = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imagenlb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        anadire = new javax.swing.JMenuItem();
        eliminare = new javax.swing.JMenuItem();
        editare = new javax.swing.JMenuItem();
        buscare = new javax.swing.JMenuItem();
        listare = new javax.swing.JMenuItem();
        inventariom = new javax.swing.JMenu();
        anadirCategoriam = new javax.swing.JMenuItem();
        eliminarCategoriam = new javax.swing.JMenuItem();
        editarCategoriam = new javax.swing.JMenuItem();
        buscarCategoriam = new javax.swing.JMenuItem();
        listarCategoriam = new javax.swing.JMenuItem();
        aa = new javax.swing.JMenu();
        anadirMedidam = new javax.swing.JMenuItem();
        eliminarMedidam = new javax.swing.JMenuItem();
        editarMedidam = new javax.swing.JMenuItem();
        buscarMedidam = new javax.swing.JMenuItem();
        listarMedidas = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        anadirProdcutom = new javax.swing.JMenuItem();
        eliminarProductom = new javax.swing.JMenuItem();
        editarProductom = new javax.swing.JMenuItem();
        buscarProductom = new javax.swing.JMenuItem();
        listarProducto = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        anadirRecetam = new javax.swing.JMenuItem();
        eliminarRecetam = new javax.swing.JMenuItem();
        editarRecetam = new javax.swing.JMenuItem();
        buscarRecetam = new javax.swing.JMenuItem();
        listarRecetasm = new javax.swing.JMenuItem();
        aaaaa = new javax.swing.JMenu();
        anadirBodegam = new javax.swing.JMenuItem();
        sumarBodegam = new javax.swing.JMenuItem();
        eliminarBodegam = new javax.swing.JMenuItem();
        editarBodegam = new javax.swing.JMenuItem();
        listarBodegam = new javax.swing.JMenuItem();
        buscarBodegam = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Restaurante Ortiz & Asociados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        nombrel.setForeground(new java.awt.Color(255, 255, 255));
        nombrel.setText("jLabel4");

        apellidol.setForeground(new java.awt.Color(255, 255, 255));
        apellidol.setText("jLabel5");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        jMenu1.setText("Empleados");

        anadire.setText("Anadir Empleado");
        anadire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadireActionPerformed(evt);
            }
        });
        jMenu1.add(anadire);

        eliminare.setText("Eliminar Empleado");
        eliminare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminareActionPerformed(evt);
            }
        });
        jMenu1.add(eliminare);

        editare.setText("Editar Empleado");
        editare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editareActionPerformed(evt);
            }
        });
        jMenu1.add(editare);

        buscare.setText("Buscar Empleado");
        buscare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscareActionPerformed(evt);
            }
        });
        jMenu1.add(buscare);

        listare.setText("Listar Empleados");
        listare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listareActionPerformed(evt);
            }
        });
        jMenu1.add(listare);

        jMenuBar1.add(jMenu1);

        inventariom.setText("Categorias");

        anadirCategoriam.setText("Anadir Categoria");
        anadirCategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirCategoriamActionPerformed(evt);
            }
        });
        inventariom.add(anadirCategoriam);

        eliminarCategoriam.setText("Eliminar Categoria");
        eliminarCategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCategoriamActionPerformed(evt);
            }
        });
        inventariom.add(eliminarCategoriam);

        editarCategoriam.setText("Editar Categoria");
        editarCategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriamActionPerformed(evt);
            }
        });
        inventariom.add(editarCategoriam);

        buscarCategoriam.setText("Buscar Categoria");
        buscarCategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCategoriamActionPerformed(evt);
            }
        });
        inventariom.add(buscarCategoriam);

        listarCategoriam.setText("Listar Categorias");
        listarCategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCategoriamActionPerformed(evt);
            }
        });
        inventariom.add(listarCategoriam);

        jMenuBar1.add(inventariom);

        aa.setText("Medidas");

        anadirMedidam.setText("Anadir Medida");
        anadirMedidam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirMedidamActionPerformed(evt);
            }
        });
        aa.add(anadirMedidam);

        eliminarMedidam.setText("Eliminar Medida");
        eliminarMedidam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMedidamActionPerformed(evt);
            }
        });
        aa.add(eliminarMedidam);

        editarMedidam.setText("Editar Medida");
        editarMedidam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMedidamActionPerformed(evt);
            }
        });
        aa.add(editarMedidam);

        buscarMedidam.setText("Buscar Medida");
        buscarMedidam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMedidamActionPerformed(evt);
            }
        });
        aa.add(buscarMedidam);

        listarMedidas.setText("Listar Medidas");
        listarMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMedidasActionPerformed(evt);
            }
        });
        aa.add(listarMedidas);

        jMenuBar1.add(aa);

        jMenu10.setText("Productos");

        anadirProdcutom.setText("Anadir Producto");
        anadirProdcutom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirProdcutomActionPerformed(evt);
            }
        });
        jMenu10.add(anadirProdcutom);

        eliminarProductom.setText("Eliminar Producto");
        eliminarProductom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductomActionPerformed(evt);
            }
        });
        jMenu10.add(eliminarProductom);

        editarProductom.setText("EditarProducto");
        editarProductom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProductomActionPerformed(evt);
            }
        });
        jMenu10.add(editarProductom);

        buscarProductom.setText("Buscar Producto");
        buscarProductom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductomActionPerformed(evt);
            }
        });
        jMenu10.add(buscarProductom);

        listarProducto.setText("Listar Productos");
        listarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProductoActionPerformed(evt);
            }
        });
        jMenu10.add(listarProducto);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Recetas");

        anadirRecetam.setText("Anadir Receta");
        anadirRecetam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirRecetamActionPerformed(evt);
            }
        });
        jMenu11.add(anadirRecetam);

        eliminarRecetam.setText("Eliminar Receta");
        eliminarRecetam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRecetamActionPerformed(evt);
            }
        });
        jMenu11.add(eliminarRecetam);

        editarRecetam.setText("Editar Receta");
        jMenu11.add(editarRecetam);

        buscarRecetam.setText("Buscar Receta");
        buscarRecetam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRecetamActionPerformed(evt);
            }
        });
        jMenu11.add(buscarRecetam);

        listarRecetasm.setText("Listar Recetas");
        listarRecetasm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarRecetasmActionPerformed(evt);
            }
        });
        jMenu11.add(listarRecetasm);

        jMenuBar1.add(jMenu11);

        aaaaa.setText("Bodega.P");

        anadirBodegam.setText("Anadir Bodega.P");
        anadirBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(anadirBodegam);

        sumarBodegam.setText("Sumar Bodega.P");
        sumarBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(sumarBodegam);

        eliminarBodegam.setText("Eliminar Bodega.P");
        eliminarBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(eliminarBodegam);

        editarBodegam.setText("Editar Bodega.P");
        editarBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(editarBodegam);

        listarBodegam.setText("Listar Bodegas.P");
        listarBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(listarBodegam);

        buscarBodegam.setText("Buscar Bodega.P");
        buscarBodegam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBodegamActionPerformed(evt);
            }
        });
        aaaaa.add(buscarBodegam);

        jMenuBar1.add(aaaaa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenlb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenlb, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadireActionPerformed
        // TODO add your handling code here:
        System.out.println("Anadir Empleado ADMINISTRADORFRAME");
        AnadirEmpleadoFrame aef = new AnadirEmpleadoFrame(ce, cs);
        aef.setVisible(true);
    }//GEN-LAST:event_anadireActionPerformed

    private void eliminareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminareActionPerformed
        // TODO add your handling code here:
        System.out.println("Eliminar Empleado ADMINISTRADORFRAME");
        EliminarEmpleadoFrame eef = new EliminarEmpleadoFrame(ce);
        eef.setVisible(true);
    }//GEN-LAST:event_eliminareActionPerformed

    private void editareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editareActionPerformed
        // TODO add your handling code here:
        System.out.println("Editar Empleado ADMINISTRADORFRAME");
        EditarEmpleadoFrame ef = new EditarEmpleadoFrame(ce, cs);
        ef.setVisible(true);
    }//GEN-LAST:event_editareActionPerformed

    private void buscareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscareActionPerformed
        // TODO add your handling code here:
        System.out.println("Buscar Empleado ADMINISTRADORFRAME");
        BuscarEmpleadosFrame bef = new BuscarEmpleadosFrame(ce);
        bef.setVisible(true);
    }//GEN-LAST:event_buscareActionPerformed

    private void listareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listareActionPerformed
        // TODO add your handling code here:
        System.out.println("Listar Empleados ADMINISTRADORFRAME");
        ListarEmpleadosFrame lef = new ListarEmpleadosFrame(ce);
        lef.setVisible(true);
    }//GEN-LAST:event_listareActionPerformed

    private void anadirCategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirCategoriamActionPerformed
        // TODO add your handling code here:
        System.out.println("AnadirCategoria ADMINISTRADORFRAME");
        AnadirCategoriaFrame acf = new AnadirCategoriaFrame(cc);
        acf.setVisible(true);
    }//GEN-LAST:event_anadirCategoriamActionPerformed

    private void listarCategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCategoriamActionPerformed
        // TODO add your handling code here:
        System.out.println("listarCategoria ADMINISTRADORFRAME");
        ListarCategoriasFrame lcf = new ListarCategoriasFrame(cc);
        lcf.setVisible(true);
                
    }//GEN-LAST:event_listarCategoriamActionPerformed

    private void editarCategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriamActionPerformed
        // TODO add your handling code here:
        System.out.println("editarCategoria ADMINISTRADORFRAME");
        EditarCategoriaFrame ecf = new EditarCategoriaFrame(cc);
        ecf.setVisible(true);
    }//GEN-LAST:event_editarCategoriamActionPerformed

    private void buscarCategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCategoriamActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarCategoria ADMINISTRADORFRAME");
        BuscarCategoriaFrame bcf = new BuscarCategoriaFrame(cc);
        bcf.setVisible(true);
    }//GEN-LAST:event_buscarCategoriamActionPerformed

    private void eliminarCategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCategoriamActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminarCategoria ADMINISTRADORFRAME");
        EliminarCategoriaFrame ecf = new EliminarCategoriaFrame(cc);
        ecf.setVisible(true);            
    }//GEN-LAST:event_eliminarCategoriamActionPerformed

    private void anadirMedidamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirMedidamActionPerformed
        // TODO add your handling code here:
        System.out.println("anadir medida ADMINISTRADORFRAME");
        AnadirTipoMedidaFrame atmf = new AnadirTipoMedidaFrame(ctm);
        atmf.setVisible(true);
    }//GEN-LAST:event_anadirMedidamActionPerformed

    private void eliminarMedidamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMedidamActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminar medida ADMINISTRADORFRAME");
        EliminarTipoMedidaFrame etmf = new EliminarTipoMedidaFrame(ctm);
        etmf.setVisible(true);
    }//GEN-LAST:event_eliminarMedidamActionPerformed

    private void editarMedidamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMedidamActionPerformed
        // TODO add your handling code here:
        System.out.println("editar medida ADMINISTRADORFRAME");
        EditarTipoMedidaFrame etmf = new EditarTipoMedidaFrame(ctm);
        etmf.setVisible(true);
    }//GEN-LAST:event_editarMedidamActionPerformed

    private void buscarMedidamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMedidamActionPerformed
        // TODO add your handling code here:
        System.out.println("buscar medida ADMINISTRADORFRAME");
        BuscarMedidaFrame bmf = new BuscarMedidaFrame(ctm);
        bmf.setVisible(true);
    }//GEN-LAST:event_buscarMedidamActionPerformed

    private void listarMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMedidasActionPerformed
        // TODO add your handling code here:
        System.out.println("listar medida ADMINISTRADORFRAME");
        ListarMedidasFrame lmf = new ListarMedidasFrame(ctm);
        lmf.setVisible(true);
    }//GEN-LAST:event_listarMedidasActionPerformed

    private void eliminarProductomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductomActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminarProductom ADMINISTRADORFRAME");
        EliminarProductoFrame epf = new EliminarProductoFrame(cp);
        epf.setVisible(true);
    }//GEN-LAST:event_eliminarProductomActionPerformed

    private void anadirProdcutomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirProdcutomActionPerformed
        // TODO add your handling code here:
        System.out.println("anadirProductom ADMINISTRADORFRAME");
        AnadirProductoFrame apf = new AnadirProductoFrame(cp);
        apf.setVisible(true);               
    }//GEN-LAST:event_anadirProdcutomActionPerformed

    private void editarProductomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProductomActionPerformed
        // TODO add your handling code here:
        System.out.println("eitarProducto ADMINISTRADORFRAME");
        EditarProductoFrame epf = new EditarProductoFrame(cp);
        epf.setVisible(true);
    }//GEN-LAST:event_editarProductomActionPerformed

    private void buscarProductomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductomActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarProducto ADMINISTRADORFRAME");
        BuscarProductoFrame bpf = new BuscarProductoFrame(cp);
        bpf.setVisible(true);
    }//GEN-LAST:event_buscarProductomActionPerformed

    private void listarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductoActionPerformed
        // TODO add your handling code here:
        System.out.println("listarProdctos ADMINISTRADORFRAME");
        ListarProductosFrame lpf = new ListarProductosFrame(cp);
        lpf.setVisible(true);
    }//GEN-LAST:event_listarProductoActionPerformed

    private void anadirRecetamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirRecetamActionPerformed
        // TODO add your handling code here:
        System.out.println("anadirReceta ADMINISTRADORFRAME");
        AnadirRecetaFrame arf = new AnadirRecetaFrame(cr, crd);
        arf.setVisible(true);
    }//GEN-LAST:event_anadirRecetamActionPerformed

    private void eliminarRecetamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRecetamActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminarReceta ADMINISTRADORFRAME");
        EliminarRecetaFrame erf = new EliminarRecetaFrame(cr);
        erf.setVisible(true);
    }//GEN-LAST:event_eliminarRecetamActionPerformed

    private void anadirBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("anadirBodegam ADMINISTRADORFRAME");
        AnadirBodegaFrame abf = new AnadirBodegaFrame(cb, cs);
        abf.setVisible(true);
    }//GEN-LAST:event_anadirBodegamActionPerformed

    private void sumarBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("sumarBpdega ADMINISTRADORFRAME");
        SumarBodegaFrame sbf = new SumarBodegaFrame(cb, cs);
        sbf.setVisible(true);
    }//GEN-LAST:event_sumarBodegamActionPerformed

    private void buscarRecetamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRecetamActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarReceta ADMINISTRADORFRAME");
        BuscarRecetaFrame brf = new BuscarRecetaFrame(cr);
        brf.setVisible(true);
    }//GEN-LAST:event_buscarRecetamActionPerformed

    private void listarRecetasmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarRecetasmActionPerformed
        // TODO add your handling code here:
        System.out.println("listarRecetas ADMINISTRADORFRAME");
        ListarRecetasFrame lrf = new ListarRecetasFrame(cr, crd);
        lrf.setVisible(true);
    }//GEN-LAST:event_listarRecetasmActionPerformed

    private void eliminarBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminarBodega ADMINISTRADORFRAME");
        EliminarBodegaFrame ebf = new EliminarBodegaFrame(cb, cs);
        ebf.setVisible(true);
        
    }//GEN-LAST:event_eliminarBodegamActionPerformed

    private void editarBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("editarBodega ADMINISTRADORFRAME");
        EditarBodegaFrame ebf = new EditarBodegaFrame(cb, cs);
        ebf.setVisible(true);
    }//GEN-LAST:event_editarBodegamActionPerformed

    private void listarBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("listarBodega ADMINISTRADORFRAME");
        ListarBodegaFrame lbf = new ListarBodegaFrame(cb);
        lbf.setVisible(true);
    }//GEN-LAST:event_listarBodegamActionPerformed

    private void buscarBodegamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBodegamActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarBodega ADMINISTRADORFRAME");
        BuscarBodegaFrame bbf = new BuscarBodegaFrame(cb, cs);
        bbf.setVisible(true);
    }//GEN-LAST:event_buscarBodegamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aa;
    private javax.swing.JMenu aaaaa;
    private javax.swing.JMenuItem anadirBodegam;
    private javax.swing.JMenuItem anadirCategoriam;
    private javax.swing.JMenuItem anadirMedidam;
    private javax.swing.JMenuItem anadirProdcutom;
    private javax.swing.JMenuItem anadirRecetam;
    private javax.swing.JMenuItem anadire;
    private javax.swing.JLabel apellidol;
    private javax.swing.JMenuItem buscarBodegam;
    private javax.swing.JMenuItem buscarCategoriam;
    private javax.swing.JMenuItem buscarMedidam;
    private javax.swing.JMenuItem buscarProductom;
    private javax.swing.JMenuItem buscarRecetam;
    private javax.swing.JMenuItem buscare;
    private javax.swing.JMenuItem editarBodegam;
    private javax.swing.JMenuItem editarCategoriam;
    private javax.swing.JMenuItem editarMedidam;
    private javax.swing.JMenuItem editarProductom;
    private javax.swing.JMenuItem editarRecetam;
    private javax.swing.JMenuItem editare;
    private javax.swing.JMenuItem eliminarBodegam;
    private javax.swing.JMenuItem eliminarCategoriam;
    private javax.swing.JMenuItem eliminarMedidam;
    private javax.swing.JMenuItem eliminarProductom;
    private javax.swing.JMenuItem eliminarRecetam;
    private javax.swing.JMenuItem eliminare;
    private javax.swing.JLabel imagenlb;
    private javax.swing.JMenu inventariom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem listarBodegam;
    private javax.swing.JMenuItem listarCategoriam;
    private javax.swing.JMenuItem listarMedidas;
    private javax.swing.JMenuItem listarProducto;
    private javax.swing.JMenuItem listarRecetasm;
    private javax.swing.JMenuItem listare;
    private javax.swing.JLabel nombrel;
    private javax.swing.JMenuItem sumarBodegam;
    // End of variables declaration//GEN-END:variables
}
