/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAdministrador;
import controlador.ControladorSucursal;
import java.awt.Color;

/**
 *
 * @author Isaac Chavez ECh
 */
public class DuenoFrame extends javax.swing.JFrame {
ControladorAdministrador cAdministrador;
ControladorSucursal cSucursal;
    /**
     * Creates new form DuenoFrame
     * @param ca
     * @param cs
     */
    public DuenoFrame(ControladorAdministrador ca, ControladorSucursal cs) {
        initComponents();
        this.getContentPane().setBackground(new Color(125,125,125));
        cAdministrador = ca;
        cSucursal = cs;
    }

    private DuenoFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulol = new javax.swing.JLabel();
        nombrel1 = new javax.swing.JLabel();
        nombrel2 = new javax.swing.JLabel();
        apellidol = new javax.swing.JLabel();
        apellidol2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        administradoresm = new javax.swing.JMenu();
        anadira = new javax.swing.JMenuItem();
        eliminara = new javax.swing.JMenuItem();
        editara = new javax.swing.JMenuItem();
        buscara = new javax.swing.JMenuItem();
        listara = new javax.swing.JMenuItem();
        sucursalesm = new javax.swing.JMenu();
        anadirs = new javax.swing.JMenuItem();
        eliminars = new javax.swing.JMenuItem();
        editars = new javax.swing.JMenuItem();
        buscars = new javax.swing.JMenuItem();
        listars = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        titulol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titulol.setForeground(new java.awt.Color(255, 255, 255));
        titulol.setText("Restaurante Ortiz & Asociados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulol, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        nombrel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombrel1.setForeground(new java.awt.Color(255, 255, 255));
        nombrel1.setText("Nombre:");

        nombrel2.setForeground(new java.awt.Color(255, 255, 255));

        apellidol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        apellidol.setForeground(new java.awt.Color(255, 255, 255));
        apellidol.setText("Apellido:");

        apellidol2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        administradoresm.setText("Administradores");

        anadira.setText("Anadir Datos Administrador");
        anadira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadiraActionPerformed(evt);
            }
        });
        administradoresm.add(anadira);

        eliminara.setText("Eliminar Datos Administrador");
        eliminara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaraActionPerformed(evt);
            }
        });
        administradoresm.add(eliminara);

        editara.setText("Editar Datos Administrador");
        editara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaraActionPerformed(evt);
            }
        });
        administradoresm.add(editara);

        buscara.setText("Buscar Administrador");
        buscara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaraActionPerformed(evt);
            }
        });
        administradoresm.add(buscara);

        listara.setText("Listar Administradores");
        listara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaraActionPerformed(evt);
            }
        });
        administradoresm.add(listara);

        jMenuBar1.add(administradoresm);

        sucursalesm.setText("Sucursales");

        anadirs.setText("Anadir Sucursal");
        anadirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirsActionPerformed(evt);
            }
        });
        sucursalesm.add(anadirs);

        eliminars.setText("Eliminar Sucursal");
        eliminars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarsActionPerformed(evt);
            }
        });
        sucursalesm.add(eliminars);

        editars.setText("Editar Sucursal");
        editars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarsActionPerformed(evt);
            }
        });
        sucursalesm.add(editars);

        buscars.setText("Buscar Sucursal");
        buscars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarsActionPerformed(evt);
            }
        });
        sucursalesm.add(buscars);

        listars.setText("Listar Sucursales");
        listars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarsActionPerformed(evt);
            }
        });
        sucursalesm.add(listars);

        jMenuBar1.add(sucursalesm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombrel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(nombrel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidol2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombrel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidol2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadiraActionPerformed
        // TODO add your handling code here:
        System.out.println("Anadir Administrador");
        AnadirAdministradorFrame aaf = new AnadirAdministradorFrame(cAdministrador, cSucursal);
        aaf.setVisible(true);
    }//GEN-LAST:event_anadiraActionPerformed

    private void eliminaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaraActionPerformed
        // TODO add your handling code here:
        System.out.println("Eliminar Administrador");
        EliminarAdministradorFrame eaf = new EliminarAdministradorFrame(cAdministrador);
        eaf.setVisible(true);
    }//GEN-LAST:event_eliminaraActionPerformed

    private void editaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaraActionPerformed
        // TODO add your handling code here:
        System.out.println("Editar Administradores");
        EditarAdministradorFrame eaf = new EditarAdministradorFrame(cAdministrador, cSucursal);
        eaf.setVisible(true);
    }//GEN-LAST:event_editaraActionPerformed

    private void buscaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaraActionPerformed
        // TODO add your handling code here:
        System.out.println("Buscar Administrador");
        BuscarAdministradorFrame baf = new BuscarAdministradorFrame(cAdministrador);
        baf.setVisible(true);
    }//GEN-LAST:event_buscaraActionPerformed

    private void listaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaraActionPerformed
        // TODO add your handling code here:
        System.out.println("Listar Administradores");
        ListarAdministradoresFrame laf = new ListarAdministradoresFrame(cAdministrador);
        laf.setVisible(true);
    }//GEN-LAST:event_listaraActionPerformed

    
    
    ///////////////////////////////////////////////////////////////////
    /////////////////////////////Sucursales////////////////////////////
    //////////////////////////////////////////////////////////////////
    private void anadirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirsActionPerformed
        // TODO add your handling code here:
        System.out.println("Anadir Sucursal");
        AnadirSucursalFrame asf = new AnadirSucursalFrame(cSucursal);
        asf.setVisible(true);
        
    }//GEN-LAST:event_anadirsActionPerformed

    private void listarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarsActionPerformed
        // TODO add your handling code here:
        System.out.println("Listar Sucursales");
    }//GEN-LAST:event_listarsActionPerformed

    private void eliminarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarsActionPerformed
        // TODO add your handling code here:
        System.out.println("Eliminar Sucursales");
    }//GEN-LAST:event_eliminarsActionPerformed

    private void editarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarsActionPerformed
        // TODO add your handling code here:
        System.out.println("Editar Sucursales");
    }//GEN-LAST:event_editarsActionPerformed

    private void buscarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarsActionPerformed
        // TODO add your handling code here:
        System.out.println("Buscar Sucursales");
    }//GEN-LAST:event_buscarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuenoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu administradoresm;
    private javax.swing.JMenuItem anadira;
    private javax.swing.JMenuItem anadirs;
    private javax.swing.JLabel apellidol;
    private javax.swing.JLabel apellidol2;
    private javax.swing.JMenuItem buscara;
    private javax.swing.JMenuItem buscars;
    private javax.swing.JMenuItem editara;
    private javax.swing.JMenuItem editars;
    private javax.swing.JMenuItem eliminara;
    private javax.swing.JMenuItem eliminars;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem listara;
    private javax.swing.JMenuItem listars;
    private javax.swing.JLabel nombrel1;
    private javax.swing.JLabel nombrel2;
    private javax.swing.JMenu sucursalesm;
    private javax.swing.JLabel titulol;
    // End of variables declaration//GEN-END:variables
}
