/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorBodega;
import controlador.ControladorCliente;
import controlador.ControladorFacturaCabecera;
import controlador.ControladorFacturaDetalle;
import controlador.ControladorMembresia;
import controlador.ControladorReceta;
import controlador.ControladorRecetaDetalle;
import controlador.ControladorSucursal;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelo.Empleado;

/**
 *
 * @author Isaac Chavez ECh
 */
public class EmpleadoFrame extends javax.swing.JFrame {
    ControladorCliente cc;
    ControladorMembresia cm;
    ControladorReceta cr;
    ControladorRecetaDetalle crd;
    ControladorFacturaCabecera cfc;
    ControladorFacturaDetalle cfd;
    ControladorBodega cb;
    ControladorSucursal cs;
    Empleado empleado;
    /**
     * Creates new form EmpleadoFrame
     * @param ccc
     * @param cmm
     * @param cr
     * @param crd
     * @param cfc
     * @param cfd
     * @param cb
     * @param cs
     * @param empleado
     */
    public EmpleadoFrame(ControladorCliente ccc, ControladorMembresia cmm, ControladorReceta cr,
            ControladorRecetaDetalle crd, ControladorFacturaCabecera cfc, ControladorFacturaDetalle cfd,
            ControladorBodega cb, ControladorSucursal cs, Empleado empleado) {
        initComponents();
        this.getContentPane().setBackground(new Color(125,125,125));
        this.cc = ccc;
        this.cm = cmm;
        this.cr = cr;
        this.crd = crd;
        this.cfc = cfc;
        this.cfd = cfd;
        this.cb = cb;
        this.cs = cs;
        this.empleado = empleado;
        nombrel.setText(empleado.getEmpUsername());
        correol.setText(empleado.getPerCorreo());
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/user (3).png"));
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(imagenlb.getWidth(), imagenlb.getHeight(),Image.SCALE_DEFAULT));
        imagenlb.setIcon(fondo);
    }

    private EmpleadoFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    EmpleadoFrame(ControladorCliente cCliente, ControladorMembresia cMembresia, ControladorReceta cReceta, ControladorRecetaDetalle cRecetaD) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imagenlb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        anadirm = new javax.swing.JMenuItem();
        eliminarm = new javax.swing.JMenuItem();
        editarm = new javax.swing.JMenuItem();
        buscarm = new javax.swing.JMenuItem();
        listarm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        anadirmembresiam = new javax.swing.JMenuItem();
        eliminarMembresiam = new javax.swing.JMenuItem();
        editarMembresiam = new javax.swing.JMenuItem();
        buscarMembresiam = new javax.swing.JMenuItem();
        listarMembresiasm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        facturarm = new javax.swing.JMenuItem();
        buscarFactura = new javax.swing.JMenuItem();
        eliminarFacturam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante Ortiz & Asociados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        nombrel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");

        correol.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        anadirm.setText("Anadir Cliente");
        anadirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirmActionPerformed(evt);
            }
        });
        jMenu1.add(anadirm);

        eliminarm.setText("Eliminar Cliente");
        eliminarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarmActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarm);

        editarm.setText("Editar Cliente");
        editarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarmActionPerformed(evt);
            }
        });
        jMenu1.add(editarm);

        buscarm.setText("Buscar Cliente");
        buscarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarmActionPerformed(evt);
            }
        });
        jMenu1.add(buscarm);

        listarm.setText("Listar Clientes");
        listarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarmActionPerformed(evt);
            }
        });
        jMenu1.add(listarm);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Membresias");

        anadirmembresiam.setText("Anadir Membresia");
        anadirmembresiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirmembresiamActionPerformed(evt);
            }
        });
        jMenu2.add(anadirmembresiam);

        eliminarMembresiam.setText("Eliminar Membresia");
        eliminarMembresiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMembresiamActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarMembresiam);

        editarMembresiam.setText("Editar Membresia");
        editarMembresiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMembresiamActionPerformed(evt);
            }
        });
        jMenu2.add(editarMembresiam);

        buscarMembresiam.setText("Buscar Membresia");
        buscarMembresiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMembresiamActionPerformed(evt);
            }
        });
        jMenu2.add(buscarMembresiam);

        listarMembresiasm.setText("Listar Membresias");
        listarMembresiasm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMembresiasmActionPerformed(evt);
            }
        });
        jMenu2.add(listarMembresiasm);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Facturacion");

        facturarm.setText("Facturar");
        facturarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarmActionPerformed(evt);
            }
        });
        jMenu3.add(facturarm);

        buscarFactura.setText("Buscar Factura");
        buscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFacturaActionPerformed(evt);
            }
        });
        jMenu3.add(buscarFactura);

        eliminarFacturam.setText("Eliminar Factura");
        eliminarFacturam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFacturamActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarFacturam);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombrel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenlb, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarmActionPerformed
        // TODO add your handling code here:
        System.out.println("Editar Cliente");
        EditarClienteFrame ecf = new EditarClienteFrame(cc);
        ecf.setVisible(true);
    }//GEN-LAST:event_editarmActionPerformed

    private void anadirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirmActionPerformed
        // TODO add your handling code here:
        System.out.println("Anadir Cliente");
        AnadirClienteFrame acf = new AnadirClienteFrame(cc);
        acf.setVisible(true);
    }//GEN-LAST:event_anadirmActionPerformed

    private void eliminarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarmActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminar Cliente");
        EliminarClienteFrame ecf = new EliminarClienteFrame(cc, cm);
        ecf.setVisible(true);
    }//GEN-LAST:event_eliminarmActionPerformed

    private void buscarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarmActionPerformed
        // TODO add your handling code here:
        System.out.println("Buscar Cliente");
        BuscarClienteFrame bcf = new BuscarClienteFrame(cc);
        bcf.setVisible(true);

    }//GEN-LAST:event_buscarmActionPerformed

    private void listarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarmActionPerformed
        // TODO add your handling code here:
        System.out.println("Listar Cliente");
        ListarClientesFrame lcf = new ListarClientesFrame(cc);
        lcf.setVisible(true);
    }//GEN-LAST:event_listarmActionPerformed

    private void anadirmembresiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirmembresiamActionPerformed
        // TODO add your handling code here:
        System.out.println("Anadir memmbresia");
        AnadirMembresiaFrame amf = new AnadirMembresiaFrame(cc, cm);
        amf.setVisible(true);
    }//GEN-LAST:event_anadirmembresiamActionPerformed

    private void eliminarMembresiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMembresiamActionPerformed
        // TODO add your handling code here:
        System.out.println("Eliminar MembresiaM");
        EliminarMembresiaFrame emf = new EliminarMembresiaFrame(cm);
        emf.setVisible(true);
    }//GEN-LAST:event_eliminarMembresiamActionPerformed

    private void buscarMembresiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMembresiamActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarMembresia EmpleadoFrame");
        BuscarMembresiaFrame bmf = new BuscarMembresiaFrame(cc, cm);
        bmf.setVisible(true);
    }//GEN-LAST:event_buscarMembresiamActionPerformed

    private void editarMembresiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMembresiamActionPerformed
        // TODO add your handling code here:
        System.out.println("editarMembresia EMPLEADOFRAME");
        EditarMembresiaFrame emf = new EditarMembresiaFrame(cc, cm);
        emf.setVisible(true);
    }//GEN-LAST:event_editarMembresiamActionPerformed

    private void listarMembresiasmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMembresiasmActionPerformed
        // TODO add your handling code here:
        System.out.println("listarMembresias EMPLEADOFRAME");
        ListarMembresiasFrame lmf = new ListarMembresiasFrame(cm);
        lmf.setVisible(true);
    }//GEN-LAST:event_listarMembresiasmActionPerformed

    private void eliminarFacturamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFacturamActionPerformed
        // TODO add your handling code here:
        System.out.println("eliminarFactura EMPLEADOFRAME");
    }//GEN-LAST:event_eliminarFacturamActionPerformed

    private void facturarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarmActionPerformed
        // TODO add your handling code here:
        System.out.println("facturar EMPLEADOFRAME");
        FacturacionFrame ff = new FacturacionFrame(cc, cm, cr, crd, cfc, cfd, cb, cs, empleado);
        ff.setVisible(true);
    }//GEN-LAST:event_facturarmActionPerformed

    private void buscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFacturaActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarFactura EMPLEADOFRAME");
    }//GEN-LAST:event_buscarFacturaActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anadirm;
    private javax.swing.JMenuItem anadirmembresiam;
    private javax.swing.JMenuItem buscarFactura;
    private javax.swing.JMenuItem buscarMembresiam;
    private javax.swing.JMenuItem buscarm;
    private javax.swing.JLabel correol;
    private javax.swing.JMenuItem editarMembresiam;
    private javax.swing.JMenuItem editarm;
    private javax.swing.JMenuItem eliminarFacturam;
    private javax.swing.JMenuItem eliminarMembresiam;
    private javax.swing.JMenuItem eliminarm;
    private javax.swing.JMenuItem facturarm;
    private javax.swing.JLabel imagenlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem listarMembresiasm;
    private javax.swing.JMenuItem listarm;
    private javax.swing.JLabel nombrel;
    // End of variables declaration//GEN-END:variables
}
