/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorBodega;
import controlador.ControladorCliente;
import controlador.ControladorFacturaCabecera;
import controlador.ControladorFacturaDetalle;
import controlador.ControladorMembresia;
import controlador.ControladorReceta;
import controlador.ControladorRecetaDetalle;
import controlador.ControladorSucursal;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Empleado;
import modelo.FacturaCabecera;
import modelo.FacturaDetalle;
import modelo.Membresia;
import modelo.Receta;
import modelo.Sucursal;

/**
 *
 * @author Isaac Chavez ECh
 */
public class FacturacionFrame extends javax.swing.JFrame {
    //Controladores
    ControladorCliente cc; 
    ControladorMembresia cm;
    ControladorReceta cr;
    ControladorRecetaDetalle crd;
    ControladorFacturaCabecera cfc;
    ControladorFacturaDetalle cfd;
    ControladorBodega cb;
    ControladorSucursal cs;
    //////////////////////////////////////////////////////////////////////////////////
    ImpresionFactura impFac;
    Object[] oenviar = new Object[4];
    /////////////////////////////////////////////////////////////////////
    //Variables del sistema
    Cliente cliente = null;
    Membresia membresia = null;
    Receta receta = null;
    Sucursal suc = null;
    //Variables del JTABLE
    DefaultTableModel dtm;
    Object[] o = new Object[4];
    int filaSelecc1ionada;
    //VARIABLES FACTURACION 
    Double subtotal = null;
    Double iva = null;
    Double descuento = null;
    Double resultado = null;
    ////////////////////////////////////////////////////////////////////////////////////////
    Boolean datosCliente=true;
    /**
     * Creates new form FacturacionFrame
     * @param cc
     * @param cm
     * @param cr
     * @param crd
     * @param cfc
     * @param cfd
     * @param cb
     * @param cs
     * @param empleado
     */
    public FacturacionFrame(ControladorCliente cc, ControladorMembresia cm, ControladorReceta cr,
             ControladorRecetaDetalle crd, ControladorFacturaCabecera cfc, ControladorFacturaDetalle cfd,
             ControladorBodega cb, ControladorSucursal cs, Empleado empleado) {
        initComponents();
        this.cc = cc;
        this.cm = cm;
        this.cr = cr;
        this.crd = crd;
        this.cfc = cfc;
        this.cfd = cfd;
        this.cb = cb;
        this.cs = cs;
        this.getContentPane().setBackground(new Color(125,125,125));
        dtm = (DefaultTableModel)table.getModel();
        listarCombox();
        fechal.setText(actualizarFecha());
        empleadol.setText(empleado.getPerNombre()+" "+empleado.getPerApellido());
    }

    private FacturacionFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Salirbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sucursalcombox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        finalch = new javax.swing.JCheckBox();
        datosch = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cedulat = new javax.swing.JTextField();
        buscarClienteBt = new javax.swing.JButton();
        RegistrarClienteBt = new javax.swing.JButton();
        comprarMembresiaBt = new javax.swing.JButton();
        renovarMembresia = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        descuentot = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        simch = new javax.swing.JCheckBox();
        nomch = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        fechal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empleadol = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        recetat = new javax.swing.JTextField();
        BuscarProductoBt = new javax.swing.JButton();
        ListarProductosbt = new javax.swing.JButton();
        AgregarProductoBt = new javax.swing.JButton();
        removerProductoBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cantidadt = new javax.swing.JTextField();
        NuevaFacturaBt = new javax.swing.JButton();
        ImprimirFacturaBt = new javax.swing.JButton();
        GuardarFacturaBt = new javax.swing.JButton();
        CalcularPagoBt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        ival = new javax.swing.JLabel();
        totalival = new javax.swing.JLabel();
        descuentol = new javax.swing.JLabel();
        totaldescuentol = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        subtotall = new javax.swing.JLabel();
        totall = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Facturacion Ortiz & Asociados");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante Ortiz & Asociados");

        Salirbt.setBackground(new java.awt.Color(102, 102, 102));
        Salirbt.setForeground(new java.awt.Color(255, 255, 255));
        Salirbt.setText("Salir");
        Salirbt.setBorder(null);
        Salirbt.setBorderPainted(false);
        Salirbt.setContentAreaFilled(false);
        Salirbt.setFocusPainted(false);
        Salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salirbt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(Salirbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(80, 80, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sucursal:");

        sucursalcombox.setBackground(new java.awt.Color(80, 80, 80));
        sucursalcombox.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Consumidor:");

        finalch.setBackground(new java.awt.Color(80, 80, 80));
        finalch.setForeground(new java.awt.Color(255, 255, 255));
        finalch.setText("Final");

        datosch.setBackground(new java.awt.Color(80, 80, 80));
        datosch.setForeground(new java.awt.Color(255, 255, 255));
        datosch.setText("Con Datos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cedula Cliente:");

        buscarClienteBt.setBackground(new java.awt.Color(80, 80, 80));
        buscarClienteBt.setForeground(new java.awt.Color(255, 255, 255));
        buscarClienteBt.setText("Buscar Cliente");
        buscarClienteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteBtActionPerformed(evt);
            }
        });

        RegistrarClienteBt.setBackground(new java.awt.Color(80, 80, 80));
        RegistrarClienteBt.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarClienteBt.setText("Registrar Cliente");
        RegistrarClienteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClienteBtActionPerformed(evt);
            }
        });

        comprarMembresiaBt.setBackground(new java.awt.Color(80, 80, 80));
        comprarMembresiaBt.setForeground(new java.awt.Color(255, 255, 255));
        comprarMembresiaBt.setText("Comprar Membresia");
        comprarMembresiaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarMembresiaBtActionPerformed(evt);
            }
        });

        renovarMembresia.setBackground(new java.awt.Color(80, 80, 80));
        renovarMembresia.setForeground(new java.awt.Color(255, 255, 255));
        renovarMembresia.setText("Renovar Membresia");
        renovarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovarMembresiaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descuento E:");

        descuentot.setText("0.0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Membresia: ");

        simch.setBackground(new java.awt.Color(80, 80, 80));
        simch.setForeground(new java.awt.Color(255, 255, 255));
        simch.setText("Si");
        simch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simchActionPerformed(evt);
            }
        });

        nomch.setBackground(new java.awt.Color(80, 80, 80));
        nomch.setForeground(new java.awt.Color(255, 255, 255));
        nomch.setText("No");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(finalch)
                                .addGap(18, 18, 18)
                                .addComponent(datosch))
                            .addComponent(sucursalcombox, 0, 172, Short.MAX_VALUE)
                            .addComponent(cedulat))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descuentot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(simch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomch))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buscarClienteBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegistrarClienteBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comprarMembresiaBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(renovarMembresia)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucursalcombox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalch)
                    .addComponent(datosch)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simch)
                    .addComponent(nomch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descuentot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarClienteBt)
                    .addComponent(RegistrarClienteBt)
                    .addComponent(comprarMembresiaBt)
                    .addComponent(renovarMembresia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha: ");

        fechal.setForeground(new java.awt.Color(255, 255, 255));
        fechal.setText("12/11/2019");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Empleado:");

        empleadol.setForeground(new java.awt.Color(255, 255, 255));
        empleadol.setText("Willaim Sinchi");

        jPanel4.setBackground(new java.awt.Color(80, 80, 80));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Producto:");

        BuscarProductoBt.setBackground(new java.awt.Color(80, 80, 80));
        BuscarProductoBt.setForeground(new java.awt.Color(255, 255, 255));
        BuscarProductoBt.setText("Buscar Producto");
        BuscarProductoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProductoBtActionPerformed(evt);
            }
        });

        ListarProductosbt.setBackground(new java.awt.Color(80, 80, 80));
        ListarProductosbt.setForeground(new java.awt.Color(255, 255, 255));
        ListarProductosbt.setText("Lista Productos");
        ListarProductosbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProductosbtActionPerformed(evt);
            }
        });

        AgregarProductoBt.setBackground(new java.awt.Color(80, 80, 80));
        AgregarProductoBt.setForeground(new java.awt.Color(255, 255, 255));
        AgregarProductoBt.setText("Agregar Producto");
        AgregarProductoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoBtActionPerformed(evt);
            }
        });

        removerProductoBt.setBackground(new java.awt.Color(80, 80, 80));
        removerProductoBt.setForeground(new java.awt.Color(255, 255, 255));
        removerProductoBt.setText("Remover Producto");
        removerProductoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProductoBtActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad:");

        cantidadt.setText("1");
        cantidadt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadtActionPerformed(evt);
            }
        });

        NuevaFacturaBt.setBackground(new java.awt.Color(80, 80, 80));
        NuevaFacturaBt.setForeground(new java.awt.Color(255, 255, 255));
        NuevaFacturaBt.setText("Nueva Factura");
        NuevaFacturaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaFacturaBtActionPerformed(evt);
            }
        });

        ImprimirFacturaBt.setBackground(new java.awt.Color(80, 80, 80));
        ImprimirFacturaBt.setForeground(new java.awt.Color(255, 255, 255));
        ImprimirFacturaBt.setText("Imprimir Factura");
        ImprimirFacturaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirFacturaBtActionPerformed(evt);
            }
        });

        GuardarFacturaBt.setBackground(new java.awt.Color(80, 80, 80));
        GuardarFacturaBt.setForeground(new java.awt.Color(255, 255, 255));
        GuardarFacturaBt.setText("Guardar Factura");
        GuardarFacturaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFacturaBtActionPerformed(evt);
            }
        });

        CalcularPagoBt.setBackground(new java.awt.Color(80, 80, 80));
        CalcularPagoBt.setForeground(new java.awt.Color(255, 255, 255));
        CalcularPagoBt.setText("Calcular Pago");
        CalcularPagoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPagoBtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pago Detalle:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IVA:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total IVA:");

        d.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setText("Descuento:");

        y.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        y.setForeground(new java.awt.Color(255, 255, 255));
        y.setText("Total: Descuento:");

        ival.setForeground(new java.awt.Color(255, 255, 255));
        ival.setText("12");

        totalival.setForeground(new java.awt.Color(255, 255, 255));
        totalival.setText("000.00");

        descuentol.setForeground(new java.awt.Color(255, 255, 255));
        descuentol.setText("000.00");

        totaldescuentol.setForeground(new java.awt.Color(255, 255, 255));
        totaldescuentol.setText("000.00");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Subtotal:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Total:");

        subtotall.setForeground(new java.awt.Color(255, 255, 255));
        subtotall.setText("000.00");

        totall.setForeground(new java.awt.Color(255, 255, 255));
        totall.setText("000.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ival, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(283, 283, 283))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(CalcularPagoBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GuardarFacturaBt)
                                .addGap(10, 10, 10)
                                .addComponent(ImprimirFacturaBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NuevaFacturaBt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recetat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(BuscarProductoBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ListarProductosbt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgregarProductoBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removerProductoBt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(d, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(y, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totaldescuentol, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(descuentol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalival, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtotall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totall, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recetat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarProductoBt)
                    .addComponent(ListarProductosbt)
                    .addComponent(AgregarProductoBt)
                    .addComponent(removerProductoBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevaFacturaBt)
                    .addComponent(ImprimirFacturaBt)
                    .addComponent(CalcularPagoBt)
                    .addComponent(GuardarFacturaBt))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ival, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalival, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descuentol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotall, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaldescuentol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totall, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empleadol, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtActionPerformed
        // TODO add your handling code here:
        System.out.println("salir FACTURACIONFRAME");
        this.dispose();
    }//GEN-LAST:event_SalirbtActionPerformed

    private void buscarClienteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteBtActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarCliente FACTURACIONFRAME");
        cliente = cc.buscarCliente(cedulat.getText());
        membresia = cm.buscarMembresia(cedulat.getText());
        if(cliente != null && membresia != null){
            JOptionPane.showMessageDialog(null, "El cliente se encuentra disponible y posee membresia: \n"
                    + "Datos: \n"
                    + "Nombres: "+cliente.getPerNombre()+" "+cliente.getPerApellido()+" \n"
                            + "Cedula: "+cliente.getPerCedula()+" \n"
                            + "Correo: "+cliente.getPerCorreo()+" \n"
                            + "Saldo Membresia disponible: "+membresia.getMemSaldo());
        }else if(cliente != null && membresia == null){
            JOptionPane.showMessageDialog(null, "El cliente se encuentra disponible y no posee membresia: \n"
                    + "Datos: \n"
                    + "Nombres: "+cliente.getPerNombre()+" "+cliente.getPerApellido()+" \n"
                            + "Cedula: "+cliente.getPerCedula()+" \n"
                            + "Correo: "+cliente.getPerCorreo());
        }else if (cliente == null && membresia == null){
            JOptionPane.showMessageDialog(null, "El cliente no esta registrado");
        }
    }//GEN-LAST:event_buscarClienteBtActionPerformed

    private void RegistrarClienteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClienteBtActionPerformed
        // TODO add your handling code here:
        System.out.println("RegistraCliente FACTURACIONFRAME");
        AnadirClienteFrame acf = new AnadirClienteFrame(cc);
        acf.setVisible(true);
    }//GEN-LAST:event_RegistrarClienteBtActionPerformed

    private void comprarMembresiaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarMembresiaBtActionPerformed
        // TODO add your handling code here:
        System.out.println("comprarMembresia");
        AnadirMembresiaFrame amf = new AnadirMembresiaFrame(cc, cm);
        amf.setVisible(true);
    }//GEN-LAST:event_comprarMembresiaBtActionPerformed

    private void renovarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovarMembresiaActionPerformed
        // TODO add your handling code here:
        System.out.println("renovarMembresia FACTURACIONFRAME");
        RenovarMembresiaFrame rmf = new RenovarMembresiaFrame(cm);
        rmf.setVisible(true);
    }//GEN-LAST:event_renovarMembresiaActionPerformed

    private void BuscarProductoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductoBtActionPerformed
        // TODO add your handling code here:
        System.out.println("buscarProducto FACTURACIONFRAME");
        receta = cr.buscarReceta(recetat.getText());
        if(receta!=null){
            JOptionPane.showMessageDialog(null, "Producto Encontrado:");
            //recetat.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Receta no encontrada");
        }
    }//GEN-LAST:event_BuscarProductoBtActionPerformed

    private void ListarProductosbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProductosbtActionPerformed
        // TODO add your handling code here:
        System.out.println("listarProductos FacturacionFrame");
        ListarRecetasFrame lrf = new ListarRecetasFrame(cr, crd);
        lrf.setVisible(true);
    }//GEN-LAST:event_ListarProductosbtActionPerformed

    private void AgregarProductoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoBtActionPerformed
        // TODO add your handling code here:
        System.out.println("AgregarProducto FACTURACIONFRAME");
        if(receta!=null){
            Double mul = receta.getPrecio()*Double.parseDouble(cantidadt.getText());
            o[0] = receta.getNombre();
            o[1] = receta.getPrecio();
            o[2] = cantidadt.getText();
            o[3] = mul;
            dtm.addRow(o);
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese un Nombre de producto valido");
        }
    }//GEN-LAST:event_AgregarProductoBtActionPerformed

    private void removerProductoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProductoBtActionPerformed
        // TODO add your handling code here:
        System.out.println("removerProducto FACTURACIONFRAME");
        if(table.getSelectedRow() != -1){
            dtm.removeRow(table.getSelectedRow());
        }else{
           JOptionPane.showMessageDialog(null, "Por Favor selecciona una columna");
        }
          
    }//GEN-LAST:event_removerProductoBtActionPerformed

    private void cantidadtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadtActionPerformed

    private void CalcularPagoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPagoBtActionPerformed
        // TODO add your handling code here:
        System.out.println("CalcularPago FACTURACIONFRAME");
        ArrayList<Double> list = sumarColumna();
        subtotal = cfc.calcularSubTotal(list);
        iva = cfc.calcularIVA(subtotal, Double.parseDouble(ival.getText()));
        descuento = cfc.calcularDescuento(Double.parseDouble(descuentot.getText()), list);
        resultado = cfc.calcularTotal(iva, descuento, subtotal);
        totalival.setText(String.valueOf(iva));
        descuentol.setText(descuentot.getText());
        totaldescuentol.setText(String.valueOf(descuento));
        subtotall.setText(String.valueOf(subtotal));
        totall.setText(String.valueOf(resultado));
        
        
    }//GEN-LAST:event_CalcularPagoBtActionPerformed

    private void GuardarFacturaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFacturaBtActionPerformed
        // TODO add your handling code here:
        suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
        System.out.println("GuardarFacturaBt FACTURACIONFRAME");
        //Factura con datos
        if(datosch.isSelected() && !finalch.isSelected()){   
            System.out.println("Factura con datos");
            //3 tipos de facturacion
            if(cliente != null){
                //tieneMembresia
                /////////////////////
                ////////////////////////
                if(simch.isSelected() && membresia != null ){
                    System.out.println("tiene membresia");
                    if(subtotal!=null && resultado!=null && iva!=null && cliente!=null){
                        FacturaCabecera fc = new FacturaCabecera(0, null, subtotal, resultado, iva, null, cliente);
                        suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                        if(cfc.anadirFacturaCabecera(fc, suc)==true && cm.restarMembresia(membresia)==true){
                            int id = cfc.buscarId(cliente.getPerId());
                            //System.out.println(id+"aqui");
                            ArrayList<FacturaDetalle>facd = mandarDetalle();
                            suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                            if(cfd.anadirDetalle(facd, id)==true && cb.restarBodega(facd, suc)==true){
                                JOptionPane.showMessageDialog(null, "Transaccion realizada con exito");
                                cfc.listarCabeceras();
                                cfd.listarDetalles();
                                ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                datosCliente=true;
                            }else{
                                JOptionPane.showMessageDialog(null, "No se pudo realizar la transaccion");
                            }
                    }else{
                         JOptionPane.showMessageDialog(null, "Por favor calcula los valores antes de agregar la factura");
                         }   
                    }
 
                //No tiene membresia 
                /////////////////////
                ////////////////////
                }else if(nomch.isSelected()){
                    System.out.println("No tiene membresia");
                    if(subtotal!=null && resultado!=null && iva!=null && cliente!=null){
                        FacturaCabecera fc = new FacturaCabecera(0, null, subtotal, resultado, iva, null, cliente);
                        suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                        if(cfc.anadirFacturaCabecera(fc, suc)==true){
                            int id = cfc.buscarId(cliente.getPerId());
                            System.out.println(id+"aqui");
                            ArrayList<FacturaDetalle>facd = mandarDetalle();
                            suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                            if(cfd.anadirDetalle(facd, id)==true && cb.restarBodega(facd, suc)==true){
                                JOptionPane.showMessageDialog(null, "Transaccion realizada con exito");
                                cfc.listarCabeceras();
                                cfd.listarDetalles();
                                /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                datosCliente=true;
                            }else{
                                JOptionPane.showMessageDialog(null, "No se pudo realizar la transaccion");
                            }

                    }else{
                         JOptionPane.showMessageDialog(null, "Por favor calcula los valores antes de agregar la factura");
                    }
                 
   
                    }
                }
                
                if(cliente != null && membresia == null){
                    //////
                    /////
                    ////
                    ////
                }
                
                if (cliente == null && membresia == null){
                    JOptionPane.showMessageDialog(null, "Por Favor busca un usuario registrado");
                }
            
            
                if((simch.isSelected() && nomch.isSelected())) {
                       JOptionPane.showMessageDialog(null, "Por selecciona un solo item en el campo membresia"); 
                }
                
                if((!simch.isSelected() && !nomch.isSelected())) {
                       JOptionPane.showMessageDialog(null, "Por selecciona un item en el campo membresia"); 
                }
            }
        }
        //////////////////////////////////////
        //////////////////////////////////////
        //////////////////////////////////////
        //Consumidor Final
        if(finalch.isSelected() && !datosch.isSelected()){
            System.out.println("Consumidor Final");
            if(subtotal!=null && resultado!=null && iva!=null){ 
                suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                FacturaCabecera fc2 = new FacturaCabecera(0, null, subtotal, resultado, iva, null, null);
                if(cfc.anadirFacturaCabeceraFinal(fc2, suc)==true){ 
                    System.out.println("hATA AQUI");
                    //busco id factura
                    int id = cfc.buscarId(3);
                    //System.out.println(id+"aqui");
                    //array obtenido al sustraer datos del JTable
                    ArrayList<FacturaDetalle>facd = mandarDetalle();
                    suc = cs.buscarSucursal((String)sucursalcombox.getSelectedItem());
                    if(cfd.anadirDetalle(facd, id)==true && cb.restarBodega(facd, suc)==true){
                        JOptionPane.showMessageDialog(null, "Transaccion realizada con exito");
                        cfc.listarCabeceras();
                        cfd.listarDetalles();
                        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                        datosCliente=false;
                    }else{
                        JOptionPane.showMessageDialog(null, "No se pudo realizar la transaccion");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la transaccion");
                }
            }    
        /////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////
            if(finalch.isSelected() && datosch.isSelected()){
                JOptionPane.showMessageDialog(null, "Por favor selecciona un solo item en el campo Tipo de Consumidor");
            }
        
            if(!finalch.isSelected() && !datosch.isSelected()){
                JOptionPane.showMessageDialog(null, "Por favor selecciona un  item en el campo Tipo de Consumidor");
            }
        }
        
        
        //HERE HERE
        /////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////
        if(finalch.isSelected() && datosch.isSelected()){
            JOptionPane.showMessageDialog(null, "Por favor selecciona un solo item en el campo Tipo de Consumidor");
        }
        
        if(!finalch.isSelected() && !datosch.isSelected()){
            JOptionPane.showMessageDialog(null, "Por favor selecciona un  item en el campo Tipo de Consumidor");
        }
        
        
    }//GEN-LAST:event_GuardarFacturaBtActionPerformed

    private void simchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_simchActionPerformed

    private void NuevaFacturaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaFacturaBtActionPerformed
        // TODO add your handling code here:
        System.out.println("NuevaFactura FACTURACIONFRAME");
        cliente = null;
        membresia = null;
        receta = null;
        subtotal = null;
        iva = null;
        descuento = null;
        resultado = null;
        totalival.setText("00.00");
        descuentol.setText("00.00");
        totaldescuentol.setText("00.00");
        subtotall.setText("00.00");
        totall.setText("00.00");
        cedulat.setText("");
        descuentot.setText("0.0");
        recetat.setText("");
        cantidadt.setText("");
        dtm.setRowCount(0);
    }//GEN-LAST:event_NuevaFacturaBtActionPerformed

    private void ImprimirFacturaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirFacturaBtActionPerformed
        // TODO add your handling code here:
        impFac= new ImpresionFactura();
            if(datosCliente==true)
                impFac.agregarClienteConDatos(cliente.getPerId(),subtotal,iva,descuento);
            else if(datosCliente==false)
                impFac.consumidorFinal(subtotal,iva,descuento);
            
            
            for(int i =0; i<table.getRowCount();i++){
                oenviar[0] = table.getValueAt(i, 0).toString();
                oenviar[1] = Double.parseDouble(table.getValueAt(i, 1).toString());
                oenviar[2] = Integer.parseInt(table.getValueAt(i, 2).toString());
                oenviar[3] = Double.parseDouble(table.getValueAt(i, 3).toString());;
                
                impFac.agregarProducto(oenviar);
            }
            
            
            impFac.setVisible(true);
    }//GEN-LAST:event_ImprimirFacturaBtActionPerformed

    /**
     * Obtiene los datos de la columna total y los almacena en un array
     * @return 
     */
    private ArrayList<Double> sumarColumna(){
        ArrayList<Double> total = new ArrayList<Double>();
        Double c;
        for(int i =0;i<table.getRowCount();i++){
            c = Double.parseDouble(table.getValueAt(i, 3).toString());
            //System.out.println(c);
            total.add(c);
        }
        
        return total;
    }
    
    
    private ArrayList<FacturaDetalle> mandarDetalle(){
        ArrayList<FacturaDetalle> fdd = new ArrayList<>();
        for(int i =0; i<table.getRowCount();i++){
            Receta rec = cr.buscarReceta(table.getValueAt(i, 0).toString());
            Double precio = Double.parseDouble(table.getValueAt(i, 1).toString());
            int cantidad = Integer.parseInt(table.getValueAt(i, 2).toString());
            Double total = Double.parseDouble(table.getValueAt(i, 3).toString());
            FacturaDetalle fd = new FacturaDetalle(0, cantidad, total, precio, rec, descuento);
            fdd.add(fd);
        }
        return fdd;
    }
    
    
    private String actualizarFecha(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }
    
    private void listarCombox(){
        ArrayList<Sucursal> suc = cs.listarSucursales();
        for(int i=0;i<suc.size();i++){
            sucursalcombox.addItem(suc.get(i).getSucNombre());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturacionFrame().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProductoBt;
    private javax.swing.JButton BuscarProductoBt;
    private javax.swing.JButton CalcularPagoBt;
    private javax.swing.JButton GuardarFacturaBt;
    private javax.swing.JButton ImprimirFacturaBt;
    private javax.swing.JButton ListarProductosbt;
    private javax.swing.JButton NuevaFacturaBt;
    private javax.swing.JButton RegistrarClienteBt;
    private javax.swing.JButton Salirbt;
    private javax.swing.JButton buscarClienteBt;
    private javax.swing.JTextField cantidadt;
    private javax.swing.JTextField cedulat;
    private javax.swing.JButton comprarMembresiaBt;
    private javax.swing.JLabel d;
    private javax.swing.JCheckBox datosch;
    private javax.swing.JLabel descuentol;
    private javax.swing.JTextField descuentot;
    private javax.swing.JLabel empleadol;
    private javax.swing.JLabel fechal;
    private javax.swing.JCheckBox finalch;
    private javax.swing.JLabel ival;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox nomch;
    private javax.swing.JTextField recetat;
    private javax.swing.JButton removerProductoBt;
    private javax.swing.JButton renovarMembresia;
    private javax.swing.JCheckBox simch;
    private javax.swing.JLabel subtotall;
    private javax.swing.JComboBox<String> sucursalcombox;
    private javax.swing.JTable table;
    private javax.swing.JLabel totaldescuentol;
    private javax.swing.JLabel totalival;
    private javax.swing.JLabel totall;
    private javax.swing.JLabel y;
    // End of variables declaration//GEN-END:variables
}
