/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAdministrador;
import controlador.ControladorBodega;
import controlador.ControladorCategoria;
import controlador.ControladorCliente;
import controlador.ControladorEmpleado;
import controlador.ControladorFacturaCabecera;
import controlador.ControladorFacturaDetalle;
import controlador.ControladorMembresia;
import controlador.ControladorProducto;
import controlador.ControladorReceta;
import controlador.ControladorRecetaDetalle;
import controlador.ControladorSucursal;
import controlador.ControladorTipoMedida;
import java.util.ArrayList;

import modelo.Administrador;
import modelo.Empleado;

/**
 *
 * @author Isaac Chavez ECh
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private final ControladorAdministrador cAdministrador = new ControladorAdministrador();
    private final ControladorSucursal cSucursal = new ControladorSucursal();
    private final ControladorEmpleado cEmpleado = new ControladorEmpleado();
    private final ControladorCliente cCliente = new ControladorCliente(); 
    private final ControladorMembresia cMembresia = new ControladorMembresia();
    private final ControladorCategoria cCategoria = new ControladorCategoria();
    private final ControladorTipoMedida cMedida = new ControladorTipoMedida();
    private final ControladorProducto cProducto = new ControladorProducto(cCategoria, cMedida);
    private final ControladorReceta cReceta = new ControladorReceta();
    private final ControladorRecetaDetalle cRecetaD = new ControladorRecetaDetalle(cProducto, cReceta);
    private final ControladorBodega cBodega = new ControladorBodega(cProducto);
    private final ControladorFacturaCabecera cCabecera = new ControladorFacturaCabecera(cCliente);
    private final ControladorFacturaDetalle cDetalle = new ControladorFacturaDetalle(cReceta, cCabecera);
    private final ArrayList<Administrador> aList;
    private final ArrayList<Empleado> eList;
    Administrador admin = null;
    Empleado empleado = null;
    //private final rayList<MemArrayList<Cliente> cList;
    //private final Arbresia> mList;
    
    String name = "ortiz";
    String psw = "1234";

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        aList = cAdministrador.listarAdministradores();
        eList = cEmpleado.listarEmpleados();
        cCliente.listarClientes();
        cMembresia.listarMembresias();
        cCategoria.listarCategorias();
        cMedida.listarMedidas();
        cProducto.listarProductos();
        cReceta.listarRecetas();
        cRecetaD.listarTodasRecetas();
        cBodega.listarBodega();
        cCabecera.listarCabeceras();
        cDetalle.listarDetalles();
        cSucursal.listarSucursales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usernamet = new javax.swing.JTextField();
        paswort = new javax.swing.JPasswordField();
        usernamel = new javax.swing.JLabel();
        pasworl = new javax.swing.JLabel();
        aceptarbt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante Ortiz & Asociados");
        setBackground(java.awt.SystemColor.activeCaptionText);

        jPanel3.setBackground(new java.awt.Color(125, 125, 125));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        usernamet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametActionPerformed(evt);
            }
        });

        usernamel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usernamel.setForeground(new java.awt.Color(255, 255, 255));
        usernamel.setText("UserName:");

        pasworl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pasworl.setForeground(new java.awt.Color(255, 255, 255));
        pasworl.setText("Pasword:");

        aceptarbt.setBackground(new java.awt.Color(102, 102, 102));
        aceptarbt.setForeground(new java.awt.Color(255, 255, 255));
        aceptarbt.setText("Aceptar");
        aceptarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarbtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("V.1.0.0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/work-team (5).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptarbt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernamel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasworl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernamet, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(paswort))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasworl)
                    .addComponent(paswort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarbt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante Ortiz & Asociados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametActionPerformed

    private void aceptarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarbtActionPerformed
        // TODO add your handling code here:
        System.out.println(aceptarbt.getActionCommand());
        String nombre = usernamet.getText();
        String contrasena = paswort.getText();
        //Login del DuenoFrame del/os restaurante/s
        if(nombre.equalsIgnoreCase(name)==true && contrasena.equalsIgnoreCase(psw)){
            System.out.println("Dueno Conectado");
            DuenoFrame dueno = new DuenoFrame(cAdministrador, cSucursal);
            this.setVisible(false);
            dueno.setVisible(true);
            usernamet.setText("");
            paswort.setText("");
        //Login para Administradores    
        }else if(validarAdministrador(nombre,contrasena) == true){
            AdministradorFrame af = new AdministradorFrame(cEmpleado, cCategoria,cMedida,cProducto,
                                                            cReceta, cRecetaD, cBodega, cSucursal, admin);
            this.setVisible(false);
            af.setVisible(true);
            usernamet.setText("");
            paswort.setText("");
         //Login para Empleados
         
        }else if(validarEmpleados(nombre, contrasena)==true){
            
            EmpleadoFrame ef = new EmpleadoFrame(cCliente, cMembresia, cReceta, cRecetaD, cCabecera, cDetalle,
            cBodega, cSucursal, empleado);
            this.setVisible(false);
            ef.setVisible(true);
            usernamet.setText("");
            paswort.setText("");
        }else{
            System.out.println("no entra"); 
        }
        
    
        
    }//GEN-LAST:event_aceptarbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    private boolean validarAdministrador(String nombre, String psw){
        boolean b = false;
        Administrador adm = null;
        
        for(int i=0; i<aList.size();i++){
            Administrador aux = aList.get(i);
            if(aux.getAdmUsername().equalsIgnoreCase(nombre)==true && aux.getAdmPasword().equalsIgnoreCase(psw)==true){
                adm = aux;
                admin = adm;
                break;
            }
        }
        
        if(adm != null){
            String[] parts = adm.getAdmUsername().split("_");
            String part1 = parts[0]; 
            String part2 = parts[1]; 
            if(part2.equalsIgnoreCase("adm")){
                b = true;
            }
        }
        
        return b;            
    }
    
    
    private boolean validarEmpleados(String nombre, String psw){
        boolean b = false;
        Empleado adm = null;
        
        for(int i=0; i<eList.size();i++){
            Empleado aux = eList.get(i);
            if(aux.getEmpUsername().equalsIgnoreCase(nombre)==true && aux.getEmpPassword().equalsIgnoreCase(psw)==true){
                adm = aux;
                empleado = adm;
                break;
            }
        }
        
        if(adm != null){
            String[] parts = adm.getEmpUsername().split("_");
            String part1 = parts[0]; 
            String part2 = parts[1]; 
            if(part2.equalsIgnoreCase("emp")){
                b = true;
            }
        }
        
        return b;            
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pasworl;
    private javax.swing.JPasswordField paswort;
    private javax.swing.JLabel usernamel;
    private javax.swing.JTextField usernamet;
    // End of variables declaration//GEN-END:variables
}
